apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: new-pod1-sbasa
  name: new-pod1
  namespace: sbasa
spec:
  containers:
  - image: nginx
    name: new-pod1-sbasa


---
apiVersion: v1
kind: Service
metadata:
  name: rest-simpleapp-svc
  namespace: sbasa
spec:
  type: NodePort
  selector:
    run: new-pod1-sbasa
  ports:
    - port: 8088
      targetPort: 80 
      nodePort: 32000
